// <auto-generated />
using System;
using DropCommerce.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DropCommerce.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DropCommerceDbContext))]
    partial class DropCommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<long>("DropEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_event_id");

                    b.Property<long?>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_name");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("new_values");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OldValues")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("old_values");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_log_auditoria");

                    b.HasIndex("DropEventId")
                        .HasDatabaseName("ix_log_auditoria_drop_event_id");

                    b.HasIndex("EntityName")
                        .HasDatabaseName("ix_log_auditoria_entity_name");

                    b.ToTable("log_auditoria", (string)null);
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropCoupon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount_value");

                    b.Property<long>("DropCouponTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_coupon_type_id");

                    b.Property<long>("DropEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_event_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsExclusiveToRegistered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_exclusive_to_registered");

                    b.Property<bool>("IsSingleUse")
                        .HasColumnType("boolean")
                        .HasColumnName("is_single_use");

                    b.Property<decimal>("MaxDiscountCap")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_discount_cap");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer")
                        .HasColumnName("max_uses");

                    b.Property<decimal>("MinOrderValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("min_order_value");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer")
                        .HasColumnName("used_count");

                    b.HasKey("Id")
                        .HasName("pk_cupom");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_cupom_code");

                    b.HasIndex("DropCouponTypeId")
                        .HasDatabaseName("ix_cupom_drop_coupon_type_id");

                    b.HasIndex("DropEventId")
                        .HasDatabaseName("ix_cupom_drop_event_id");

                    b.ToTable("cupom", (string)null);
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BannerImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("banner_image_url");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cover_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DropEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("drop_ends_at");

                    b.Property<long>("DropEventStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_event_status_id");

                    b.Property<DateTime>("DropStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("drop_starts_at");

                    b.Property<long>("EnterpriseId")
                        .HasColumnType("bigint")
                        .HasColumnName("enterprise_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("QueueOpensAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queue_opens_at");

                    b.Property<DateTime>("RegistrationEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_ends_at");

                    b.Property<DateTime>("RegistrationStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_starts_at");

                    b.Property<bool>("RequiresRegistration")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_registration");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<int>("TotalUnitsAvailable")
                        .HasColumnType("integer")
                        .HasColumnName("total_units_available");

                    b.Property<int>("UnitsReserved")
                        .HasColumnType("integer")
                        .HasColumnName("units_reserved");

                    b.Property<int>("UnitsSold")
                        .HasColumnType("integer")
                        .HasColumnName("units_sold");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_evento");

                    b.HasIndex("DropEventStatusId")
                        .HasDatabaseName("ix_evento_drop_event_status_id");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_evento_enterprise_id");

                    b.HasIndex("Slug")
                        .HasDatabaseName("ix_evento_slug");

                    b.ToTable("evento", (string)null);
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("DropEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_event_id");

                    b.Property<long>("DropNotificationChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_notification_channel_id");

                    b.Property<long>("DropNotificationStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_notification_status_id");

                    b.Property<long>("DropNotificationTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_notification_type_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notificacao");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_notificacao_customer_id");

                    b.HasIndex("DropEventId")
                        .HasDatabaseName("ix_notificacao_drop_event_id");

                    b.HasIndex("DropNotificationChannelId")
                        .HasDatabaseName("ix_notificacao_drop_notification_channel_id");

                    b.HasIndex("DropNotificationStatusId")
                        .HasDatabaseName("ix_notificacao_drop_notification_status_id");

                    b.HasIndex("DropNotificationTypeId")
                        .HasDatabaseName("ix_notificacao_drop_notification_type_id");

                    b.ToTable("notificacao", (string)null);
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<long?>("DropCouponId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_coupon_id");

                    b.Property<long>("DropEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_event_id");

                    b.Property<long>("DropOrderPaymentStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_order_payment_status_id");

                    b.Property<long>("DropOrderStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_order_status_id");

                    b.Property<long>("DropReservationId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_reservation_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("ShippingAddressLine")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("shipping_address_line");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("shipping_city");

                    b.Property<decimal>("ShippingCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("shipping_cost");

                    b.Property<string>("ShippingState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("shipping_state");

                    b.Property<string>("ShippingZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("shipping_zip_code");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sub_total");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pedido");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_pedido_customer_id");

                    b.HasIndex("DropCouponId")
                        .HasDatabaseName("ix_pedido_drop_coupon_id");

                    b.HasIndex("DropEventId")
                        .HasDatabaseName("ix_pedido_drop_event_id");

                    b.HasIndex("DropOrderPaymentStatusId")
                        .HasDatabaseName("ix_pedido_drop_order_payment_status_id");

                    b.HasIndex("DropOrderStatusId")
                        .HasDatabaseName("ix_pedido_drop_order_status_id");

                    b.HasIndex("DropReservationId")
                        .HasDatabaseName("ix_pedido_drop_reservation_id");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropOrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DropOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_order_id");

                    b.Property<long>("DropProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_product_id");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("item_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_price");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_item_pedido");

                    b.HasIndex("DropOrderId")
                        .HasDatabaseName("ix_item_pedido_drop_order_id");

                    b.HasIndex("DropProductId")
                        .HasDatabaseName("ix_item_pedido_drop_product_id");

                    b.ToTable("item_pedido", (string)null);
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("DropEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_event_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("MaxPerCustomer")
                        .HasColumnType("integer")
                        .HasColumnName("max_per_customer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<int>("UnitsAllocated")
                        .HasColumnType("integer")
                        .HasColumnName("units_allocated");

                    b.Property<int>("UnitsSold")
                        .HasColumnType("integer")
                        .HasColumnName("units_sold");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_produto");

                    b.HasIndex("DropEventId")
                        .HasDatabaseName("ix_produto_drop_event_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_produto_product_id");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropRegistration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("DropEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_event_id");

                    b.Property<long>("DropRegistrationStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_registration_status_id");

                    b.Property<DateTime?>("EligibilityCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eligibility_checked_at");

                    b.Property<string>("EligibilityReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("eligibility_reason");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_eligible");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inscricao");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_inscricao_customer_id");

                    b.HasIndex("DropEventId")
                        .HasDatabaseName("ix_inscricao_drop_event_id");

                    b.HasIndex("DropRegistrationStatusId")
                        .HasDatabaseName("ix_inscricao_drop_registration_status_id");

                    b.ToTable("inscricao", (string)null);
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropReservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("DropEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_event_id");

                    b.Property<long>("DropProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_product_id");

                    b.Property<long>("DropReservationStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_reservation_status_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LockToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lock_token");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<long>("QueueEntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("queue_entry_id");

                    b.Property<DateTime>("ReservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_at");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reserva");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_reserva_customer_id");

                    b.HasIndex("DropEventId")
                        .HasDatabaseName("ix_reserva_drop_event_id");

                    b.HasIndex("DropProductId")
                        .HasDatabaseName("ix_reserva_drop_product_id");

                    b.HasIndex("DropReservationStatusId")
                        .HasDatabaseName("ix_reserva_drop_reservation_status_id");

                    b.HasIndex("QueueEntryId")
                        .HasDatabaseName("ix_reserva_queue_entry_id");

                    b.ToTable("reserva", (string)null);
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<long>("DropOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_order_id");

                    b.Property<long>("DropTransactionMethodId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_transaction_method_id");

                    b.Property<long>("DropTransactionStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_transaction_status_id");

                    b.Property<long>("DropTransactionTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_transaction_type_id");

                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fee");

                    b.Property<string>("GatewayPayload")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("gateway_payload");

                    b.Property<string>("GatewayProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gateway_provider");

                    b.Property<string>("GatewayReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("gateway_reference");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refunded_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_transacao");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_transacao_customer_id");

                    b.HasIndex("DropOrderId")
                        .HasDatabaseName("ix_transacao_drop_order_id");

                    b.HasIndex("DropTransactionMethodId")
                        .HasDatabaseName("ix_transacao_drop_transaction_method_id");

                    b.HasIndex("DropTransactionStatusId")
                        .HasDatabaseName("ix_transacao_drop_transaction_status_id");

                    b.HasIndex("DropTransactionTypeId")
                        .HasDatabaseName("ix_transacao_drop_transaction_type_id");

                    b.ToTable("transacao", (string)null);
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.FraudSignal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("DeviceFingerprint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("device_fingerprint");

                    b.Property<long>("DropEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_event_id");

                    b.Property<long>("FraudSeverityId")
                        .HasColumnType("bigint")
                        .HasColumnName("fraud_severity_id");

                    b.Property<long>("FraudSignalTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("fraud_signal_type_id");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_confirmed");

                    b.Property<long>("QueueEntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("queue_entry_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("WasBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("was_blocked");

                    b.HasKey("Id")
                        .HasName("pk_sinal_fraude");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sinal_fraude_customer_id");

                    b.HasIndex("DropEventId")
                        .HasDatabaseName("ix_sinal_fraude_drop_event_id");

                    b.HasIndex("FraudSeverityId")
                        .HasDatabaseName("ix_sinal_fraude_fraud_severity_id");

                    b.HasIndex("FraudSignalTypeId")
                        .HasDatabaseName("ix_sinal_fraude_fraud_signal_type_id");

                    b.HasIndex("QueueEntryId")
                        .HasDatabaseName("ix_sinal_fraude_queue_entry_id");

                    b.ToTable("sinal_fraude", (string)null);
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.QueueEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("called_at");

                    b.Property<DateTime?>("CheckedOutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_out_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<string>("DeviceFingerprint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("device_fingerprint");

                    b.Property<long>("DropEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_event_id");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entered_at");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<long>("QueueEntryStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("queue_entry_status_id");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("session_token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_entrada_fila");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_entrada_fila_customer_id");

                    b.HasIndex("DropEventId")
                        .HasDatabaseName("ix_entrada_fila_drop_event_id");

                    b.HasIndex("QueueEntryStatusId")
                        .HasDatabaseName("ix_entrada_fila_queue_entry_status_id");

                    b.ToTable("entrada_fila", (string)null);
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.QueueSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<DateTime>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<long>("QueueEntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("queue_entry_id");

                    b.Property<long>("QueueSessionStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("queue_session_status_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sessao_fila");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sessao_fila_customer_id");

                    b.HasIndex("QueueEntryId")
                        .HasDatabaseName("ix_sessao_fila_queue_entry_id");

                    b.HasIndex("QueueSessionStatusId")
                        .HasDatabaseName("ix_sessao_fila_queue_session_status_id");

                    b.ToTable("sessao_fila", (string)null);
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.WaitlistEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<long>("DropEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_event_id");

                    b.Property<long?>("DropProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("drop_product_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("boolean")
                        .HasColumnName("notification_sent");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notified_at");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("WaitlistEntryStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("waitlist_entry_status_id");

                    b.HasKey("Id")
                        .HasName("pk_entrada_lista_espera");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_entrada_lista_espera_customer_id");

                    b.HasIndex("DropEventId")
                        .HasDatabaseName("ix_entrada_lista_espera_drop_event_id");

                    b.HasIndex("DropProductId")
                        .HasDatabaseName("ix_entrada_lista_espera_drop_product_id");

                    b.HasIndex("WaitlistEntryStatusId")
                        .HasDatabaseName("ix_entrada_lista_espera_waitlist_entry_status_id");

                    b.ToTable("entrada_lista_espera", (string)null);
                });

            modelBuilder.Entity("DropCommerce.Domain.StaticEntity.DropCouponType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_tipo_cupom");

                    b.ToTable("tipo_cupom", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Percentual"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Valor fixo"
                        });
                });

            modelBuilder.Entity("DropCommerce.Domain.StaticEntity.DropEventStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_status_evento");

                    b.ToTable("status_evento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Rascunho"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Inscrições abertas"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Inscrições encerradas"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Fila aberta"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Ativo"
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Esgotado"
                        },
                        new
                        {
                            Id = 7L,
                            Description = "Encerrado"
                        },
                        new
                        {
                            Id = 8L,
                            Description = "Cancelado"
                        });
                });

            modelBuilder.Entity("DropCommerce.Domain.StaticEntity.DropNotificationChannel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_canal_notificacao");

                    b.ToTable("canal_notificacao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "E-mail"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "SMS"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Push"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "WhatsApp"
                        });
                });

            modelBuilder.Entity("DropCommerce.Domain.StaticEntity.DropNotificationStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_status_notificacao");

                    b.ToTable("status_notificacao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Agendado"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Enviado"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Entregue"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Falhou"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Devolvido"
                        });
                });

            modelBuilder.Entity("DropCommerce.Domain.StaticEntity.DropNotificationType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_tipo_notificacao");

                    b.ToTable("tipo_notificacao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Inscrição confirmada"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Abertura da fila"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Chamado na fila"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Reserva expirando"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Pedido confirmado"
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Disponível na lista de espera"
                        });
                });

            modelBuilder.Entity("DropCommerce.Domain.StaticEntity.DropOrderPaymentStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_status_pagamento_pedido");

                    b.ToTable("status_pagamento_pedido", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Pendente"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Pago"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Reembolso parcial"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Reembolso total"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Falhou"
                        });
                });

            modelBuilder.Entity("DropCommerce.Domain.StaticEntity.DropOrderStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_status_pedido");

                    b.ToTable("status_pedido", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Pendente"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Confirmado"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Em processamento"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Enviado"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Entregue"
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Cancelado"
                        },
                        new
                        {
                            Id = 7L,
                            Description = "Reembolsado"
                        });
                });

            modelBuilder.Entity("DropCommerce.Domain.StaticEntity.DropRegistrationStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_status_inscricao");

                    b.ToTable("status_inscricao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Pendente"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Elegível"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Inelegível"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Na lista de espera"
                        });
                });

            modelBuilder.Entity("DropCommerce.Domain.StaticEntity.DropReservationStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_status_reserva");

                    b.ToTable("status_reserva", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Ativa"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Confirmada"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Expirada"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Cancelada"
                        });
                });

            modelBuilder.Entity("DropCommerce.Domain.StaticEntity.DropTransactionMethod", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_metodo_transacao");

                    b.ToTable("metodo_transacao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Cartão de crédito"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Pix"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Boleto"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Carteira"
                        });
                });

            modelBuilder.Entity("DropCommerce.Domain.StaticEntity.DropTransactionStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_status_transacao");

                    b.ToTable("status_transacao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Pendente"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Autorizado"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Capturado"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Falhou"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Cancelado"
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Reembolsado"
                        });
                });

            modelBuilder.Entity("DropCommerce.Domain.StaticEntity.DropTransactionType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_tipo_transacao");

                    b.ToTable("tipo_transacao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Pagamento"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Reembolso"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Reembolso parcial"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Chargeback"
                        });
                });

            modelBuilder.Entity("DropCommerce.Domain.StaticEntity.FraudSeverity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_severidade_fraude");

                    b.ToTable("severidade_fraude", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Baixa"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Média"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Alta"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Crítica"
                        });
                });

            modelBuilder.Entity("DropCommerce.Domain.StaticEntity.FraudSignalType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_tipo_sinal_fraude");

                    b.ToTable("tipo_sinal_fraude", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "IP duplicado"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Dispositivo duplicado"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Comportamento de bot"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Múltiplas contas"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "VPN detectada"
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Velocidade anormal"
                        });
                });

            modelBuilder.Entity("DropCommerce.Domain.StaticEntity.QueueEntryStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_status_entrada_fila");

                    b.ToTable("status_entrada_fila", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Aguardando"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Chamado"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Finalizando compra"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Concluído"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Expirado"
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Removido"
                        });
                });

            modelBuilder.Entity("DropCommerce.Domain.StaticEntity.QueueSessionStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_status_sessao_fila");

                    b.ToTable("status_sessao_fila", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Ativa"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Expirada"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Invalidada"
                        });
                });

            modelBuilder.Entity("DropCommerce.Domain.StaticEntity.WaitlistEntryStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_status_lista_espera");

                    b.ToTable("status_lista_espera", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Aguardando"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Notificado"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Expirado"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Atendido"
                        });
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropAuditLog", b =>
                {
                    b.HasOne("DropCommerce.Domain.Entity.DropEvent", "DropEvent")
                        .WithMany("ListDropAuditLog")
                        .HasForeignKey("DropEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_log_auditoria_evento_drop_event_id");

                    b.Navigation("DropEvent");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropCoupon", b =>
                {
                    b.HasOne("DropCommerce.Domain.StaticEntity.DropCouponType", "DropCouponType")
                        .WithMany()
                        .HasForeignKey("DropCouponTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cupom_tipo_cupom_drop_coupon_type_id");

                    b.HasOne("DropCommerce.Domain.Entity.DropEvent", "DropEvent")
                        .WithMany("ListDropCoupon")
                        .HasForeignKey("DropEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cupom_evento_drop_event_id");

                    b.Navigation("DropCouponType");

                    b.Navigation("DropEvent");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropEvent", b =>
                {
                    b.HasOne("DropCommerce.Domain.StaticEntity.DropEventStatus", "DropEventStatus")
                        .WithMany()
                        .HasForeignKey("DropEventStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_evento_status_evento_drop_event_status_id");

                    b.Navigation("DropEventStatus");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropNotification", b =>
                {
                    b.HasOne("DropCommerce.Domain.Entity.DropEvent", "DropEvent")
                        .WithMany("ListDropNotification")
                        .HasForeignKey("DropEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notificacao_evento_drop_event_id");

                    b.HasOne("DropCommerce.Domain.StaticEntity.DropNotificationChannel", "DropNotificationChannel")
                        .WithMany()
                        .HasForeignKey("DropNotificationChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notificacao_canal_notificacao_drop_notification_channel_id");

                    b.HasOne("DropCommerce.Domain.StaticEntity.DropNotificationStatus", "DropNotificationStatus")
                        .WithMany()
                        .HasForeignKey("DropNotificationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notificacao_status_notificacao_drop_notification_status_id");

                    b.HasOne("DropCommerce.Domain.StaticEntity.DropNotificationType", "DropNotificationType")
                        .WithMany()
                        .HasForeignKey("DropNotificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notificacao_tipo_notificacao_drop_notification_type_id");

                    b.Navigation("DropEvent");

                    b.Navigation("DropNotificationChannel");

                    b.Navigation("DropNotificationStatus");

                    b.Navigation("DropNotificationType");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropOrder", b =>
                {
                    b.HasOne("DropCommerce.Domain.Entity.DropCoupon", "DropCoupon")
                        .WithMany("ListDropOrder")
                        .HasForeignKey("DropCouponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pedido_cupom_drop_coupon_id");

                    b.HasOne("DropCommerce.Domain.Entity.DropEvent", "DropEvent")
                        .WithMany("ListDropOrder")
                        .HasForeignKey("DropEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_evento_drop_event_id");

                    b.HasOne("DropCommerce.Domain.StaticEntity.DropOrderPaymentStatus", "DropOrderPaymentStatus")
                        .WithMany()
                        .HasForeignKey("DropOrderPaymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_status_pagamento_pedido_drop_order_payment_status_id");

                    b.HasOne("DropCommerce.Domain.StaticEntity.DropOrderStatus", "DropOrderStatus")
                        .WithMany()
                        .HasForeignKey("DropOrderStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_status_pedido_drop_order_status_id");

                    b.HasOne("DropCommerce.Domain.Entity.DropReservation", "DropReservation")
                        .WithMany("ListDropOrder")
                        .HasForeignKey("DropReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_reserva_drop_reservation_id");

                    b.Navigation("DropCoupon");

                    b.Navigation("DropEvent");

                    b.Navigation("DropOrderPaymentStatus");

                    b.Navigation("DropOrderStatus");

                    b.Navigation("DropReservation");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropOrderItem", b =>
                {
                    b.HasOne("DropCommerce.Domain.Entity.DropOrder", "DropOrder")
                        .WithMany("ListDropOrderItem")
                        .HasForeignKey("DropOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_item_pedido_pedido_drop_order_id");

                    b.HasOne("DropCommerce.Domain.Entity.DropProduct", "DropProduct")
                        .WithMany("ListDropOrderItem")
                        .HasForeignKey("DropProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_item_pedido_produto_drop_product_id");

                    b.Navigation("DropOrder");

                    b.Navigation("DropProduct");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropProduct", b =>
                {
                    b.HasOne("DropCommerce.Domain.Entity.DropEvent", "DropEvent")
                        .WithMany("ListDropProduct")
                        .HasForeignKey("DropEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_produto_evento_drop_event_id");

                    b.Navigation("DropEvent");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropRegistration", b =>
                {
                    b.HasOne("DropCommerce.Domain.Entity.DropEvent", "DropEvent")
                        .WithMany("ListDropRegistration")
                        .HasForeignKey("DropEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inscricao_evento_drop_event_id");

                    b.HasOne("DropCommerce.Domain.StaticEntity.DropRegistrationStatus", "DropRegistrationStatus")
                        .WithMany()
                        .HasForeignKey("DropRegistrationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inscricao_status_inscricao_drop_registration_status_id");

                    b.Navigation("DropEvent");

                    b.Navigation("DropRegistrationStatus");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropReservation", b =>
                {
                    b.HasOne("DropCommerce.Domain.Entity.DropEvent", "DropEvent")
                        .WithMany("ListDropReservation")
                        .HasForeignKey("DropEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reserva_evento_drop_event_id");

                    b.HasOne("DropCommerce.Domain.Entity.DropProduct", "DropProduct")
                        .WithMany("ListDropReservation")
                        .HasForeignKey("DropProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reserva_produto_drop_product_id");

                    b.HasOne("DropCommerce.Domain.StaticEntity.DropReservationStatus", "DropReservationStatus")
                        .WithMany()
                        .HasForeignKey("DropReservationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reserva_status_reserva_drop_reservation_status_id");

                    b.HasOne("DropCommerce.Domain.Entity.QueueEntry", "QueueEntry")
                        .WithMany("ListDropReservation")
                        .HasForeignKey("QueueEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reserva_entrada_fila_queue_entry_id");

                    b.Navigation("DropEvent");

                    b.Navigation("DropProduct");

                    b.Navigation("DropReservationStatus");

                    b.Navigation("QueueEntry");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropTransaction", b =>
                {
                    b.HasOne("DropCommerce.Domain.Entity.DropOrder", "DropOrder")
                        .WithMany("ListDropTransaction")
                        .HasForeignKey("DropOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transacao_pedido_drop_order_id");

                    b.HasOne("DropCommerce.Domain.StaticEntity.DropTransactionMethod", "DropTransactionMethod")
                        .WithMany()
                        .HasForeignKey("DropTransactionMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transacao_metodo_transacao_drop_transaction_method_id");

                    b.HasOne("DropCommerce.Domain.StaticEntity.DropTransactionStatus", "DropTransactionStatus")
                        .WithMany()
                        .HasForeignKey("DropTransactionStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transacao_status_transacao_drop_transaction_status_id");

                    b.HasOne("DropCommerce.Domain.StaticEntity.DropTransactionType", "DropTransactionType")
                        .WithMany()
                        .HasForeignKey("DropTransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transacao_tipo_transacao_drop_transaction_type_id");

                    b.Navigation("DropOrder");

                    b.Navigation("DropTransactionMethod");

                    b.Navigation("DropTransactionStatus");

                    b.Navigation("DropTransactionType");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.FraudSignal", b =>
                {
                    b.HasOne("DropCommerce.Domain.Entity.DropEvent", "DropEvent")
                        .WithMany("ListFraudSignal")
                        .HasForeignKey("DropEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sinal_fraude_evento_drop_event_id");

                    b.HasOne("DropCommerce.Domain.StaticEntity.FraudSeverity", "FraudSeverity")
                        .WithMany()
                        .HasForeignKey("FraudSeverityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sinal_fraude_severidade_fraude_fraud_severity_id");

                    b.HasOne("DropCommerce.Domain.StaticEntity.FraudSignalType", "FraudSignalType")
                        .WithMany()
                        .HasForeignKey("FraudSignalTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sinal_fraude_tipo_sinal_fraude_fraud_signal_type_id");

                    b.HasOne("DropCommerce.Domain.Entity.QueueEntry", "QueueEntry")
                        .WithMany("ListFraudSignal")
                        .HasForeignKey("QueueEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sinal_fraude_entrada_fila_queue_entry_id");

                    b.Navigation("DropEvent");

                    b.Navigation("FraudSeverity");

                    b.Navigation("FraudSignalType");

                    b.Navigation("QueueEntry");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.QueueEntry", b =>
                {
                    b.HasOne("DropCommerce.Domain.Entity.DropEvent", "DropEvent")
                        .WithMany("ListQueueEntry")
                        .HasForeignKey("DropEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entrada_fila_evento_drop_event_id");

                    b.HasOne("DropCommerce.Domain.StaticEntity.QueueEntryStatus", "QueueEntryStatus")
                        .WithMany()
                        .HasForeignKey("QueueEntryStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entrada_fila_status_entrada_fila_queue_entry_status_id");

                    b.Navigation("DropEvent");

                    b.Navigation("QueueEntryStatus");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.QueueSession", b =>
                {
                    b.HasOne("DropCommerce.Domain.Entity.QueueEntry", "QueueEntry")
                        .WithMany("ListQueueSession")
                        .HasForeignKey("QueueEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessao_fila_entrada_fila_queue_entry_id");

                    b.HasOne("DropCommerce.Domain.StaticEntity.QueueSessionStatus", "QueueSessionStatus")
                        .WithMany()
                        .HasForeignKey("QueueSessionStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessao_fila_status_sessao_fila_queue_session_status_id");

                    b.Navigation("QueueEntry");

                    b.Navigation("QueueSessionStatus");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.WaitlistEntry", b =>
                {
                    b.HasOne("DropCommerce.Domain.Entity.DropEvent", "DropEvent")
                        .WithMany("ListWaitlistEntry")
                        .HasForeignKey("DropEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entrada_lista_espera_evento_drop_event_id");

                    b.HasOne("DropCommerce.Domain.Entity.DropProduct", "DropProduct")
                        .WithMany("ListWaitlistEntry")
                        .HasForeignKey("DropProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_entrada_lista_espera_produto_drop_product_id");

                    b.HasOne("DropCommerce.Domain.StaticEntity.WaitlistEntryStatus", "WaitlistEntryStatus")
                        .WithMany()
                        .HasForeignKey("WaitlistEntryStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entrada_lista_espera_status_lista_espera_waitlist_entry_sta~");

                    b.Navigation("DropEvent");

                    b.Navigation("DropProduct");

                    b.Navigation("WaitlistEntryStatus");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropCoupon", b =>
                {
                    b.Navigation("ListDropOrder");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropEvent", b =>
                {
                    b.Navigation("ListDropAuditLog");

                    b.Navigation("ListDropCoupon");

                    b.Navigation("ListDropNotification");

                    b.Navigation("ListDropOrder");

                    b.Navigation("ListDropProduct");

                    b.Navigation("ListDropRegistration");

                    b.Navigation("ListDropReservation");

                    b.Navigation("ListFraudSignal");

                    b.Navigation("ListQueueEntry");

                    b.Navigation("ListWaitlistEntry");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropOrder", b =>
                {
                    b.Navigation("ListDropOrderItem");

                    b.Navigation("ListDropTransaction");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropProduct", b =>
                {
                    b.Navigation("ListDropOrderItem");

                    b.Navigation("ListDropReservation");

                    b.Navigation("ListWaitlistEntry");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.DropReservation", b =>
                {
                    b.Navigation("ListDropOrder");
                });

            modelBuilder.Entity("DropCommerce.Domain.Entity.QueueEntry", b =>
                {
                    b.Navigation("ListDropReservation");

                    b.Navigation("ListFraudSignal");

                    b.Navigation("ListQueueSession");
                });
#pragma warning restore 612, 618
        }
    }
}
